In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/30-days-of-ml/sample_submission.csv
/kaggle/input/30-days-of-ml/train.csv
/kaggle/input/30-days-of-ml/test.csv

## Input

In [2]:
train_full=pd.read_csv("/kaggle/input/30-days-of-ml/train.csv")
test_full=pd.read_csv("/kaggle/input/30-days-of-ml/test.csv")
sample_submission=pd.read_csv("/kaggle/input/30-days-of-ml/sample_submission.csv")

# EDA

In [3]:
test_full.describe()

,id,cont0,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,249970.884580,0.526858,0.460882,0.491686,0.496263,0.492200,0.509944,0.468050,0.537617,0.497587,0.474630,0.473625,0.473589,0.492756,0.508303
std,144169.245904,0.230506,0.213896,0.252852,0.219304,0.240251,0.228100,0.210167,0.218197,0.239337,0.217558,0.255307,0.221844,0.247105,0.222977
min,0.000000,-0.117993,-0.069316,-0.056095,0.130655,0.255903,0.045921,-0.224613,0.203763,-0.260236,0.117894,0.048734,0.052615,-0.074201,0.151052
25%,125316.750000,0.405787,0.310536,0.302189,0.328865,0.284188,0.353682,0.342813,0.356482,0.332762,0.306940,0.274991,0.308495,0.288094,0.300697
50%,249997.000000,0.496602,0.427656,0.503075,0.464590,0.395080,0.488378,0.429819,0.505216,0.438716,0.434610,0.460042,0.433857,0.422065,0.472446
75%,374649.750000,0.666389,0.615041,0.648234,0.663401,0.697252,0.668586,0.573861,0.703289,0.605368,0.610768,0.690143,0.642201,0.711038,0.758496
max,499995.000000,1.058434,0.887253,1.034687,1.039558,1.055423,1.067641,1.111540,1.032823,1.040208,0.982928,1.055955,1.071445,0.975032,0.906013

In [4]:
train_full.describe()

,id,cont0,cont1,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,target
count,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000,300000.000000
mean,250018.576947,0.527335,0.460926,0.490498,0.496689,0.491654,0.510526,0.467476,0.537119,0.498456,0.474872,0.474492,0.473216,0.494561,0.508273,8.241979
std,144450.150010,0.230599,0.214003,0.253346,0.219199,0.240074,0.228232,0.210331,0.218140,0.239920,0.218007,0.255949,0.222022,0.247292,0.222950,0.746555
min,1.000000,-0.118039,-0.069309,-0.056104,0.130676,0.255908,0.045915,-0.224689,0.203763,-0.260275,0.117896,0.048732,0.052608,-0.074208,0.151050,0.140329
25%,124772.500000,0.405965,0.310494,0.300604,0.329783,0.284188,0.354141,0.342873,0.355825,0.332486,0.306874,0.276017,0.308151,0.289074,0.300669,7.742071
50%,250002.500000,0.497053,0.427903,0.502462,0.465026,0.390470,0.488865,0.429383,0.504661,0.439151,0.434620,0.459975,0.433812,0.422887,0.472400,8.191373
75%,375226.500000,0.668060,0.615113,0.647512,0.664451,0.696599,0.669625,0.573383,0.703441,0.606056,0.614333,0.691579,0.642057,0.714502,0.758447,8.728634
max,499999.000000,1.058443,0.887253,1.034704,1.039560,1.055424,1.067649,1.111552,1.032837,1.040229,0.982922,1.055960,1.071444,0.975035,0.905992,10.411992

In [5]:
train_full.describe()-test_full.describe()

,cont0,cont1,cont10,cont11,cont12,cont13,cont2,cont3,cont4,cont5,cont6,cont7,cont8,cont9,id,target
count,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,1.000000e+05,100000.000000,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,NaN
mean,0.000477,4.330230e-05,0.000867,-0.000373,0.001804,-0.000031,-0.001188,0.000426,-5.459731e-04,0.000582,-0.000574,-4.971121e-04,0.000869,0.000242,47.692367,NaN
std,0.000093,1.066321e-04,0.000643,0.000178,0.000187,-0.000027,0.000494,-0.000105,-1.763595e-04,0.000131,0.000164,-5.730567e-05,0.000583,0.000449,280.904106,NaN
min,-0.000046,6.656787e-06,-0.000002,-0.000007,-0.000006,-0.000002,-0.000008,0.000020,4.759669e-06,-0.000006,-0.000076,1.399859e-07,-0.000039,0.000002,1.000000,NaN
25%,0.000178,-4.150839e-05,0.001026,-0.000344,0.000980,-0.000028,-0.001586,0.000918,-5.567417e-08,0.000459,0.000060,-6.570317e-04,-0.000276,-0.000066,-544.250000,NaN
50%,0.000451,2.462331e-04,-0.000068,-0.000045,0.000822,-0.000046,-0.000613,0.000436,-4.610192e-03,0.000487,-0.000436,-5.556167e-04,0.000434,0.000010,5.500000,NaN
75%,0.001671,7.153741e-05,0.001436,-0.000144,0.003464,-0.000049,-0.000722,0.001049,-6.529105e-04,0.001039,-0.000478,1.514951e-04,0.000687,0.003566,576.750000,NaN
max,0.000009,-2.686098e-07,0.000005,-0.000001,0.000003,-0.000021,0.000017,0.000003,1.208071e-06,0.000008,0.000012,1.405812e-05,0.000020,-0.000006,4.000000,NaN

In [6]:
train_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 26 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      300000 non-null  int64
 1   cat0    300000 non-null  object
 2   cat1    300000 non-null  object
 3   cat2    300000 non-null  object
 4   cat3    300000 non-null  object
 5   cat4    300000 non-null  object
 6   cat5    300000 non-null  object
 7   cat6    300000 non-null  object
 8   cat7    300000 non-null  object
 9   cat8    300000 non-null  object
 10  cat9    300000 non-null  object
 11  cont0   300000 non-null  float64
 12  cont1   300000 non-null  float64
 13  cont2   300000 non-null  float64
 14  cont3   300000 non-null  float64
 15  cont4   300000 non-null  float64
 16  cont5   300000 non-null  float64
 17  cont6   300000 non-null  float64
 18  cont7   300000 non-null  float64
 19  cont8   300000 non-null  float64
 20  cont9   300000 non-null  float64
 21  cont10  300000 non-null  float64
 22  cont11  300000 non-null  float64
 23  cont12  300000 non-null  float64
 24  cont13  300000 non-null  float64
 25  target  300000 non-null  float64
dtypes: float64(15), int64(1), object(10)
memory usage: 59.5+ MB

In [7]:
train_full.head()

,id,cat0,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,...,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,target
0,1,B,B,B,C,B,B,A,E,C,...,0.400361,0.160266,0.310921,0.389470,0.267559,0.237281,0.377873,0.322401,0.869850,8.113634
1,2,B,B,A,A,B,D,A,F,A,...,0.533087,0.558922,0.516294,0.594928,0.341439,0.906013,0.921701,0.261975,0.465083,8.481233
2,3,A,A,A,C,B,D,A,D,A,...,0.650609,0.375348,0.902567,0.555205,0.843531,0.748809,0.620126,0.541474,0.763846,8.364351
3,4,B,B,A,C,B,D,A,E,C,...,0.668980,0.239061,0.732948,0.679618,0.574844,0.346010,0.714610,0.540150,0.280682,8.049253
4,6,A,A,A,C,B,D,A,E,A,...,0.686964,0.420667,0.648182,0.684501,0.956692,1.000773,0.776742,0.625849,0.250823,7.972260

## Missing Values Checkings

In [8]:
# Shape of training data (num_rows, num_columns)
print(train_full.shape)

# Number of missing values in each column of training data
missing_val_count_by_column = (train_full.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0])

(300000, 26)
Series([], dtype: int64)

## Importing

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error

# Data processing

### X,y

In [10]:
y = train_full['target']
X_full=train_full.copy()
X_full.drop(['target'], axis=1, inplace=True)

### Break off validation set from training data

In [11]:
X_train_full, X_valid_full, y_train, y_valid = train_test_split(X_full, y, 
                                                                train_size=0.8, test_size=0.2,
                                                                random_state=0)

#### Column types

In [12]:
categorical_cols = [cname for cname in X_train_full.columns if
                    X_train_full[cname].dtype == "object"]


numerical_cols = [cname for cname in X_train_full.columns if 
                X_train_full[cname].dtype in ['int64', 'float64']]

my_cols = categorical_cols + numerical_cols
X_train = X_train_full[my_cols].copy()
X_valid = X_valid_full[my_cols].copy()
X_test = test_full[my_cols].copy()

### Preprocessing

In [13]:
# Preprocessing for numerical data
numerical_transformer = SimpleImputer(strategy='most_frequent')

# Preprocessing for categorical data
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

## Modeling

In [14]:
# Define the model
model=XGBRegressor(n_estimators=220,learning_rate=0.15)
clf = Pipeline(steps=[('preprocessor', preprocessor),
                     ('model', model)])
# Preprocessing of training data, fit model 
clf.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds = clf.predict(X_valid)

print('MAE:', mean_absolute_error(y_valid, preds))
print('MSE:', mean_squared_error(y_valid, preds))

MAE: 0.5749069566624035
MSE: 0.5237707531527082

In [15]:
preds_test = clf.predict(X_test)
# Save test predictions to file
output = pd.DataFrame({'id': X_test.id,
                       'target': preds_test})
output.to_csv('submission.csv', index=False)